# Generated by Django 5.2.2 on 2025-08-18 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_order_appointment_date_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('ai_moderating', 'Модератор AI'), ('ai_approved', 'Одобрен AI'), ('ai_rejected', 'Отклонен AI'), ('publish', 'Опубликован'), ('archive', 'Архив')], default='new', max_length=20, verbose_name='Статус'),
        ),
    ]
