# Generated by Django 5.2.2 on 2025-08-18 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_fix_review_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='master',
            name='address',
        ),
        migrations.RemoveField(
            model_name='master',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='service',
            name='description',
        ),
        migrations.RemoveField(
            model_name='service',
            name='image',
        ),
        migrations.AlterField(
            model_name='master',
            name='experience',
            field=models.IntegerField(default=0, verbose_name='Опыт работы (лет)'),
        ),
        migrations.AlterField(
            model_name='master',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='master',
            name='services',
            field=models.ManyToManyField(related_name='masters', to='core.service', verbose_name='Услуги'),
        ),
        migrations.AlterField(
            model_name='order',
            name='appointment_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата записи'),
        ),
        migrations.AlterField(
            model_name='service',
            name='duration',
            field=models.IntegerField(verbose_name='Длительность (мин)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=100, verbose_name='Имя автора')),
                ('text', models.TextField(verbose_name='Текст отзыва')),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='Оценка')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='core.master', verbose_name='Мастер')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
    ]
