# Generated by Django 5.2.2 on 2025-08-18 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_review_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(1, 'ужасно'), (2, 'плохо'), (3, 'средне'), (4, 'хорошо'), (5, 'отлично')], default=5, verbose_name='Рейтинг'),
        ),
    ]
