# Generated by Django 5.2.2 on 2025-08-25 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='view_count',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Количество просмотров'),
        ),
    ]
